### ISSUE TITLE
ssm install package.json: FAIL

### ISSUE THREAD

**Issue by cazelles** [StateSpaceModels/ssm#10]
ssm was installed nicely with npm, but I get the following error when trying to compile a model:

Ordinateur-Bernard-Cazelles-6:SIR-Paris bernard$ ssm install package.json 
INFO: Building the model...
gcc  -std=gnu99 -O3 -DGSL_RANGE_CHECK_OFF -I /Users/bernard/.ssm/include -o Ht.o -c Ht.c
gcc  -std=gnu99 -O3 -DGSL_RANGE_CHECK_OFF -I /Users/bernard/.ssm/include -o Q.o -c Q.c
gcc  -std=gnu99 -O3 -DGSL_RANGE_CHECK_OFF -I /Users/bernard/.ssm/include -o check_ic.o -c check_ic.c
gcc  -std=gnu99 -O3 -DGSL_RANGE_CHECK_OFF -I /Users/bernard/.ssm/include -o diff.o -c diff.c
gcc  -std=gnu99 -O3 -DGSL_RANGE_CHECK_OFF -I /Users/bernard/.ssm/include -o input.o -c input.c
gcc  -std=gnu99 -O3 -DGSL_RANGE_CHECK_OFF -I /Users/bernard/.ssm/include -o iterator.o -c iterator.c
gcc  -std=gnu99 -O3 -DGSL_RANGE_CHECK_OFF -I /Users/bernard/.ssm/include -o jac.o -c jac.c
gcc  -std=gnu99 -O3 -DGSL_RANGE_CHECK_OFF -I /Users/bernard/.ssm/include -o observed.o -c observed.c
gcc  -std=gnu99 -O3 -DGSL_RANGE_CHECK_OFF -I /Users/bernard/.ssm/include -o ode_sde.o -c ode_sde.c
gcc  -std=gnu99 -O3 -DGSL_RANGE_CHECK_OFF -I /Users/bernard/.ssm/include -o psr.o -c psr.c
gcc  -std=gnu99 -O3 -DGSL_RANGE_CHECK_OFF -I /Users/bernard/.ssm/include -o step_ekf.o -c step_ekf.c
gcc  -std=gnu99 -O3 -DGSL_RANGE_CHECK_OFF -I /Users/bernard/.ssm/include -o transform.o -c transform.c
ar -rcs libssmtpl.a Ht.o Q.o check_ic.o diff.o input.o iterator.o jac.o observed.o ode_sde.o psr.o step_ekf.o transform.o
gcc  -std=gnu99 -O3 -DGSL_RANGE_CHECK_OFF -I /Users/bernard/.ssm/include -L. -L /Users/bernard/.ssm/lib -o simul -lssmsimul -lssm -lssmtpl -lssm -lm -lgsl -lgslcblas -ljansson -lzmq
FAIL: ld: -L must be immediately followed by a directory path (no space)
FAIL: collect2: ld returned 1 exit status
FAIL: make: **\* [simul] Error 1
FAIL: could not build the model (2).

**Comment by sballesteros** [comment]
Thanks for reporting this. I had no ideas that 

> -L must be immediately followed by a directory path (no space)

I fixed that [here](https://github.com/standard-analytics/ssm/commit/0dd48d24c2aa09675b38fb836933e5a31819f5df) and published a new version (0.5.4) on the npm registry.

**Comment by cazelles** [comment]
Thanks! Now all seems OK. I will continue to learn ssm!
