### ISSUE TITLE
GSL path issue

### ISSUE THREAD

**Issue by QCaudron** [StateSpaceModels/ssm#11]
Using brew : after unlinking gsl in brew, I installed it again using your instructions ( "brew install jansson zmq gsl node" ), and have a linking issue on OSX Maverick, during "npm install -g ssm" :

> ssm@0.5.7 install /usr/local/lib/node_modules/ssm
> (cd src/C && make && make install && make clean)

gcc  -std=gnu99 -Wall -O3 -DGSL_RANGE_CHECK_OFF -I kalman -I pmcmc -I simul -I mif -I simplex -I core -o core/alloc_c.o -c core/alloc_c.c
In file included from core/alloc_c.c:19:
core/ssm.h:36:10: fatal error: 'gsl/gsl_math.h' file not found
# include <gsl/gsl_math.h>

```
     ^
```

1 error generated.
make: **\* [core/alloc_c.o] Error 1
npm ERR! weird error 2
npm ERR! not ok code 0

By default, installing GSL via brew will not link correctly. I'm still looking for the correct linking path, just thought I'd flag this first.

**Comment by sballesteros** [comment]
You are having an issue with homebrew here not ssm.
You can try `brew uninstall formula_name --force` and reinstalling after.
`ssm` does nothing special. The Makefile is [here](https://github.com/standard-analytics/ssm/blob/master/src/C/Makefile) but you can also try to compile some test code of your own.
`brew doctor` can help too.

**Comment by QCaudron** [comment]
Didn't think it was worth opening a new issue for this, but that I should flag it. npm test is failing, looking for a lib that isn't found :

```
> ssm@0.5.7 test /Users/qcaudron/Downloads/ssm-master
> (cd src && python test_Cmodel.py && python test_Ccoder.py) && (cd tests && make test && make clean) && ./node_modules/.bin/mocha

.................
----------------------------------------------------------------------
Ran 17 tests in 0.113s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.690s

OK
test -d /Users/qcaudron/Downloads/ssm-master/tests/resources/ || mkdir -p /Users/qcaudron/Downloads/ssm-master/tests/resources/; \
        ../bin/ssm install ../examples/foo/package.json -v -n --src; \
        cp ../examples/foo/bin/.data.json /Users/qcaudron/Downloads/ssm-master/tests/resources/; \
        cp ../examples/foo//package.json /Users/qcaudron/Downloads/ssm-master/tests/resources/

module.js:340
    throw err;
          ^
Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/qcaudron/Downloads/ssm-master/bin/ssm:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
cp: ../examples/foo/bin/.data.json: No such file or directory
clang -g -I.. -I. -I /Users/qcaudron/.ssm/include -Wall -DCLAR_FIXTURE_PATH=\"/Users/qcaudron/Downloads/ssm-master/tests/resources/\" -o ssmtest clar.c main.o parameters.o states.o observed.o iterators.o nav.o inputs.o data.o fitness.o calc.o -L../examples/foo/bin/C/templates -L /Users/qcaudron/.ssm/lib -lssm -lssmtpl -lssm -lm -lgsl -lgslcblas -ljansson -lzmq
ld: warning: directory not found for option '-L../examples/foo/bin/C/templates'
ld: library not found for -lssmtpl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ssmtest] Error 1
npm ERR! weird error 2
npm ERR! not ok code 0
```

**Comment by sballesteros** [comment]
to run the tests you need to 
1. clone the repo from github
2. at the root of the repo run `npm install`
3. now, you can run the tests

**Comment by QCaudron** [comment]
Will this cause any issues with the ssm that's installed through npm
install -g ?

Quentin CAUDRON

**Comment by sballesteros** [comment]
no. The tests are useful if you want to contribute to the project. From an user perspective it's noise.
