### ISSUE TITLE
installation tests

### ISSUE THREAD

**Issue by pearsonca** [StateSpaceModels/ssm#13]
To have `npm test` work, the mocha package needs to be installed.  Probably able to be resolved just by adding mocha to the list of packages you rec people install.

**Comment by sballesteros** [comment]
Thanks, but mocha is listed as [devDependencies](https://npmjs.org/doc/json.html#devDependencies) as it should be.

**Comment by pearsonca** [comment]
Be that as it may: I had to manually determine that mocha was missing from error messages -- and not some 'install this dependency' debugging message -- so either the automated installation process or directions to install are insufficient.
