### ISSUE TITLE
rename tracked property of model.reactions

### ISSUE THREAD

**Issue by sballesteros** [StateSpaceModels/ssm#14]
The `tracked` property of `model.reactions` seems to create confusion as some users think that the observation model can only observe tracked reactions (whereas it can observe _any_ states including those defined as tracked reactions).
Maybe renaming `tracked` as  `accumulatedIn` will help. 
@qcaudron feedback ?

**Comment by QCaudron** [comment]
Agreed. The keyword `tracked` is misleading. Either `accummulatedIn`, or perhaps `integrated` are quite general. For more epi-related context, perhaps just an `incidence` specifier ?

**Comment by sballesteros** [comment]
Thanks, trying to stay general and broader than epidemiology so I am afraid that `incidence` is too epi specific. `accumulated` seems to be the more general idea. In [pomp](http://cran.r-project.org/web/packages/pomp/vignettes/advanced_topics_in_pomp.pdf) they use `zeronames` and "accumulator variables" so I would suggest to go with `accumulators` (as its a list) or `accumulatedIn`.

**Comment by QCaudron** [comment]
Then probably `accumulated` is good; it's clear, and avoids camelCase. I think `zeronames` is equally unclear !

**Comment by sballesteros** [comment]
sorry just edited my comment. `accumulators` ? Like that it convey that it's a list of _states_ and still avoid the camelCase

**Comment by QCaudron** [comment]
The property is added to individual reactions. That being the case, adding the property to a reaction one at a time, I'd keep it singular. My vote would be for `accumulated`, as the reaction is just that - accumulated between timesteps. But it's not hugely important : the major change is to leave `tracked` behind, I think, to something more intuitively meaningful.

**Comment by sballesteros** [comment]
See your point. `accumulators` on the other hand helps to remember that the value has to be a list. Agreed it's not a big deal.
@tiffbogich, @JDureau any preferences ?
Will change that for the 0.7.x release.

**Comment by tiffbogich** [comment]
I prefer `accumulators` to the past tense version. past tense doesn't sounds right to me but i see the point

**Comment by JDureau** [comment]
I'd suggest sticking to mathematical concepts, hence `integrated/tor`. I prefer the past form. The `-tor` sounds cheesy to me.

**Comment by sballesteros** [comment]
@JDureau 100% agree to stick to the underlying math concepts but here it's more a vanilla sum than an integral no ? Reactions are supposed to be for discrete individuals so we literally cumulate (sum) them. To me integrated involve smtg continuous/infinitesimal (not the case here).

**Comment by sballesteros** [comment]
That being said, like we will support vanilla ODEs (the model.ode property) in the near future, `integrated` might be our best bet as it will work everywhere.

**Comment by sballesteros** [comment]
Although for ODE `integrated` is weird as _every_ equation is integrated... Maybe `accumulators` as the `ors` end clearly indicates that we refer to states variable. I vote for `accumulators`

**Comment by JDureau** [comment]
Actually you're opening a nice perspective, allowing integration in the ode or sde objects would lead to differential equations of order > 1. That's really not uncommon. It's far-fetched for the moment, but would be good to keep that door open. 

In that case it may be best to avoid potential confusion and step away from integration. What about `accumulation`? Trying to avoid `-or`

**Comment by sballesteros** [comment]
I like the `-or` as the property describe the creation of new _state variables_ whose job is to accumulate quantities. These new state variables are accumulator variables (that's their mission). Agreed it's a bit terminator kind of crap but I think it's the "right" semantic.

**Comment by JDureau** [comment]
Ok let's go for it. @tiffbogich and @QCaudron seemed to be fine with that.
