### ISSUE TITLE
print: t0 cannot be printed

### ISSUE THREAD

**Issue by sballesteros** [StateSpaceModels/ssm#2]
We can only print starting from the first data point. Not for the initial conditions (t0).
It's getting nasty because, there can be different initial time (t0) per observed variable.
I propose to discard this issue and _never_ print the initial conditions (t0).

Otherwise, we would need to do a ssm_row_t *row0 to be able to fully leverage the output functions of print.c

**Comment by JDureau** [comment]
Fully agree with that.
